### ISSUE TITLE
ValueError: total size of new array must be unchanged

### ISSUE THREAD

**Issue by d0znpp** [Zeta36/tensorflow-image-wavenet#1]
Sample 1314/1500
Traceback (most recent call last):
  File "generate.py", line 173, in <module>
    main()
  File "generate.py", line 167, in main
    write_img(out, args.img_out_path)
  File "generate.py", line 76, in write_img
    img = img.reshape(64, 64)
ValueError: total size of new array must be unchanged

**Comment by d0znpp** [comment]
Got it
--samples 4096 
required because of hardcode in generate.py reshape(64, 64)
