### ISSUE TITLE
ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments ( labels=..., logits=..., ...)

### ISSUE THREAD

**Issue by 5p4m3r** [Zeta36/tensorflow-image-wavenet#3]
If I run the train.py without altering anything I get this:

`(tensorflow) C:\tf\tensorflow-image-wavenet>python train.py --data_dir=data

Traceback (most recent call last):
  File "train.py", line 244, in <module>
    main()
  File "train.py", line 190, in main
    loss = net.loss(text_batch, args.l2_regularization_strength)
  File "C:\tf\tensorflow-image-wavenet\wavenet\model.py", line 452, in loss
    tf.reshape(shifted, [-1, self.quantization_channels]))
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\
python\ops\nn_ops.py", line 1578, in softmax_cross_entropy_with_logits
    labels, logits)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\
python\ops\nn_ops.py", line 1533, in _ensure_xent_args
    "named arguments (labels=..., logits=..., ...)" % name)
ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (
labels=..., logits=..., ...)`

**Comment by 5p4m3r** [comment]
it has to do with tensorflow 1.0 a lot has changed.

changing lines 450-455 in model.py from
              loss = tf.nn.softmax_cross_entropy_with_logits(
                    prediction,
                    tf.reshape(shifted, [-1, self.quantization_channels]))
                reduced_loss = tf.reduce_mean(loss)

                tf.scalar_summary("loss", reduced_loss)
to
               loss = tf.nn.softmax_cross_entropy_with_logits(
                   logits=prediction,
                   labels=tf.reshape(shifted, [-1, self.quantization_channels]))
                reduced_loss = tf.reduce_mean(loss)

               tf.summary.scalar("loss", reduced_loss)

helped.
